#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin:$PATH"
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.local/share/go/bin:$PATH"
export GOPATH="$HOME/.local/share/go"
export PATH="$PATH:./node_modules/.bin"
export PATH="$PATH:$HOME/Machfiles/scripts/.local/bin"
export PATH="$PATH:$HOME/bin"
export PATH="$PATH:$HOME/Repositories/awscli_manager"
#eval "$(fnm env)"
# eval "$(zoxide init zsh)"
# eval "`pip completion --zsh`"


# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
# __conda_setup="$("$HOME/.miniconda/bin/conda" 'shell.zsh' 'hook' 2> /dev/null)"
# if [ $? -eq 0 ]; then
#     eval "$__conda_setup"
# else
#     if [ -f "$HOME/.miniconda/etc/profile.d/conda.sh" ]; then
#         . "$HOME/.miniconda/etc/profile.d/conda.sh"
#     else
#         export PATH="$HOME/.miniconda/bin:$PATH"
#     fi
# fi
# unset __conda_setup
# <<< conda initialize <<<
# needed to deploy ecs
export AWS_DEFAULT_REGION=eu-west-1
# virtualenv
export WORKON_HOME="$HOME/.virtualenvs"
export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3
#export PROJECT_HOME=$HOME/Devel
export VIRTUALENVWRAPPER_SCRIPT=/usr/local/bin/virtualenvwrapper.sh
. /usr/local/bin/virtualenvwrapper_lazy.sh

